---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  VIRTUAL_ENV: '{{.ROOT_DIR}}/.venv'

includes:
  workstation: .taskfiles/workstation

tasks:

  default: task --list
